class Keyword(object):
    def __init__(self) -> None:
        self.keywords = {
            " and": ["且"],
            " as": ["作為"],
            "assert": ["斷言"],
            "break": ["中斷"],
            "class": ["類別"],
            "continue": ["繼續"],
            "del": ["刪除"],
            "def": ["定義"],
            "elif": ["不然"],
            "else": ["否則"],
            "except": ["異常"],
            " False": ["假"],
            "finally": ["最終"],
            "for": ["循環"],
            " from": ["從"],
            "global": ["全域"],
            "if": ["如果"],
            "import": ["導入"],
            " in": ["在"],
            " is": ["是"],
            "lambda": ["表達式"],
            " None": ["空"],
            "nonlocal": ["非全域"],
            " not": ["不"],
            " or": ["或"],
            " pass": ["略過"],
            "raise": ["抛出"],
            "return": ["返回"],
            " True": ["真"],
            "try": ["嘗試"],
            "while": ["當"],
            "with": ["與"],
            "yield": ["生成"],
            "self": ["自己"],
            "init": ["初始化"],
        }
